# Generated by Django 5.1.4 on 2024-12-15 12:14

import fernet_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_remove_choice_votes_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=fernet_fields.fields.EncryptedCharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=fernet_fields.fields.EncryptedCharField(max_length=200),
        ),
    ]
