# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Unit Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install coverage
        pip install -r requirements.txt
        pip install requests

    - name: Run database migrations
      run: |
        python manage.py makemigrations
        python manage.py migrate

    - name: Verify installed dependencies
      run: |
        pip list

    - name: Run tests with coverage
      run: |
        coverage run --source='.' manage.py test --verbosity=2

    - name: Generate coverage report
      run: |
        coverage report
